branches:
  only:
    - master

environment:
  nodejs_version: "LTS"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  #- npm test

build_script:
  - npm run build
